### ISSUE TITLE
Getting Bad Request error message as response

### ISSUE THREAD

**Issue by ooxaam** [zsoltk/overpasser#19]
I'm trying to call overpass-api in my java project, with following code:
```

	OverpassQuery query = new OverpassQuery()
    	        .format(JSON)
    	        .timeout(30)
    	        .filterQuery()
    	            .node()
    	            .amenity("drinking_water")
				.boundingBox(41.88659196260802, 12.488558292388916, 41.89248629819397, 12.51119613647461)
    	        .end()
    	        .output(100);
    	
    	OverpassQueryResult result = interpret(query.build());
```
And getting following error message as response:

> Response{protocol=http/1.1, code=400, message=Bad Request, url=http://overpass-api.de/api/interpreter?data=[%22out%22:%22json%22][%22timeout%22:%2230%22];%20(node[%22amenity%22%3D%22drinking_water%22](41.88659196260802,12.488558292388916,41.89248629819397,12.51119613647461);%3C;);%20out%20body%20center%20qt%20100;}

Can you please guide, how can I overhaul this issue.

**Comment by mmd-osm** [comment]
This tool generates invalid Overpass QL queries, hence the error message.

Instead of:

`["out":"json"]["timeout":"30"];` it should read `[out:json][timeout:30];`
